[2023-12-05 19:54:55,338] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:54:55] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:26,886] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:26] "GET /equipamentos?nome=A HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:29,523] ERROR log_exception() L825  Exception on /equipamento [POST] - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\api\app.py", line 78, in predict
    processed_data = svm_pipeline.transform(user_data.reshape(1, -1))
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\sklearn\utils\_available_if.py", line 33, in __get__
    raise attr_err
AttributeError: This 'Pipeline' has no attribute 'transform'
[2023-12-05 19:55:29,527] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:29] "[35m[1mPOST /equipamento HTTP/1.1[0m" 500 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:36,010] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:36] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:37,187] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:37] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:37,482] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:37] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:37,744] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:37] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:37,952] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:37] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 19:55:38,137] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 19:55:38] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:26:41,509] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.185:5000 - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:26:41,510] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:26:41,511] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:26:47,781] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 20:26:47] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:26:50,393] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 20:26:50] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:26:57,512] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 20:26:57] "GET /equipamentos?nome=teste HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:26:57,996] ERROR log_exception() L825  Exception on /equipamento [POST] - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\api\app.py", line 78, in predict
    processed_data = svm_pipeline.transform(user_data.reshape(1, -1))
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\sklearn\utils\_available_if.py", line 33, in __get__
    raise attr_err
AttributeError: This 'Pipeline' has no attribute 'transform'
[2023-12-05 20:26:58,000] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 20:26:58] "[35m[1mPOST /equipamento HTTP/1.1[0m" 500 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:27:02,904] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 20:27:02] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:57:11,048] INFO _log() L96    * Detected change in 'C:\\Users\\Felipe\\Desktop\\MVP4\\api\\model\\modelo.py', reloading - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 20:57:11,213] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:00:31,604] INFO _log() L96    * Detected change in 'C:\\Users\\Felipe\\Desktop\\MVP4\\api\\app.py', reloading - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:00:31,717] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:03,304] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.185:5000 - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:03,305] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:03,306] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:10,042] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 21:02:10] "[33mGET /carregadores HTTP/1.1[0m" 404 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:19,421] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 21:02:19] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:26,074] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 21:02:26] "GET /equipamentos?nome=Teste HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:26,609] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 21:02:26] "POST /equipamento HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 21:02:26,866] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 21:02:26] "GET /equipamentos HTTP/1.1" 200 - - call_trace=C:\Users\Felipe\Desktop\MVP4\env\Lib\site-packages\werkzeug\_internal.py L96  
